bump cryptography version to latest
signalfx/splunk-otel-python pull request #379
Opened 2024-01-03 15:17 UTC by pmcollins

# Description

Update `cryptography` dependency to latest patch version.

2024-01-03 17:59 UTC, johnbley approved these changes

2024-01-03 18:00 UTC, johnbley requested changes
... wait, what?  this doesn't change anything but whitespace?

2024-01-04 17:34 UTC, pmcollins commented
I think the rebase went sideways. Will fix.

2024-01-04 17:38 UTC, pmcollins commented
The library is already at the latest version in main. Closing.

2024-01-04 17:38 UTC, closed without merging